version: 2
jobs:
  build:
    docker:
        - image: circleci/golang:latest
    working_directory: /go/src/github.com/taion809/envoy-build-tests
    steps:
      - checkout
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o envoy .
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/taion809/envoy-build-tests
    steps:
      - checkout
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test .

  coverage:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/taion809/envoy-build-tests
    steps:
      - checkout
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go test -cover .

  release:
    docker:
        - image: circleci/golang:latest
    working_directory: /go/src/github.com/taion809/envoy-build-tests
    steps:
      - checkout
      - run:
          command: |
            wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 -O /tmp/ghrelease.tar.bz2
            tar -xvjpf /tmp/ghrelease.tar.bz2 -C /tmp
            cp /tmp/bin/linux/amd64/github-release /home/ubuntu/bin/ghrelease
            
      - setup_remote_docker
      - run: 
          command: |
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o envoy .
            cp envoy /tmp/envoy-dist
      - run: docker build --rm --no-cache -t taion809/envoy .
      - store_artifacts:
          path: /tmp/envoy-dist
      - deploy:
          command: |
            ghrelease release --tag ${CIRCLE_TAG} --user taion809 --repo envoy-build-tests --name "envoy release ${CIRCLE_TAG}"
            ghrelease upload --tag ${CIRCLE_TAG} --user taion809 --repo envoy-build-tests --name "envoy-linux-amd64" --file /tmp/envoy-dist

workflows:
  version: 2
  all:
    jobs:
      - build
      - test
      - coverage
      - release:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
            - test
            - coverage
